### ISSUE TITLE
how to include % character?

### ISSUE THREAD

**Issue by incandescentman** [abo-abo/tiny#6]
How can I include the % character in an expression I want to expand, as in 

    * TODO today's tasks [0%]

Here's a sample expression that throws an error when I expand:

    m0\n5|\n\n*** today's tasks <%(date "today" x)> [0%]\n***** TODO exercise

**Comment by abo-abo** [comment]
Use one extra `%`, i.e. `%%`. This is just as in the built-in Elisp function `format`.

**Comment by incandescentman** [comment]
Perfect, that works! Thank you!
