### ISSUE TITLE
Would you consider accepting the tiny-helper function?

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/tiny#8]
Hello,

I have been using tiny for many years. I though use it through a tiny-helper function sitting in my config. I use tiny.el but at times there are huge time gaps in-between and I forget the exact tiny syntax. That's where this helper has come to a great use. 

https://github.com/kaushalmodi/.emacs.d/blob/master/setup-files/setup-tiny.el

Would you accept that for inclusion in tiny.el? If so, I can start work on refactoring it to make it PR-ready.

**Comment by abo-abo** [comment]
Looks good, thanks in advance.

**Comment by kaushalmodi** [comment]
Thanks! PR submiited: https://github.com/abo-abo/tiny/pull/9
